### ISSUE TITLE
Add support for initial dry-runs to role

### ISSUE THREAD

**Issue by christianhueserhzdr** [hifis-net/ansible-role-redis#72]
The role will fail in initial dry-runs if package build-essential is not installed on instance.

Since something like `ignore_errors: "{{ is_initial_dryrun }}"`   is not recommended and even discouraged by ansible-lint:

> ignore-errors: Use failed_when and specify error conditions instead of using ignore_errors. (warning)

It can be solved by registering the task output and checking for "failed == true" like this:
```
  register: output
  failed_when: "not is_initial_dryrun and output.failed == true"
```

Source: https://ansible-lint.readthedocs.io/rules/ignore-errors/

/cc Tobias @tobiashuste and Norman @Normo, do you agree?

**Comment by tobiashuste** [comment]
What about simply skipping the job imstead using `when`?

**Comment by Normo** [comment]
The ansible-lint doc  says also this:
> Instead of using the ignore_errors: true directive, you should do the following:
>   * Ignore errors only when using the `{{ ansible_check_mode }}` variable.

Since we are not simply using ` ignore_errors: true` (which is of course a bad idea) and the boolean variable  `is_initial_dryrun` will depend on `{{ ansible_check_mode }}`  there is no need to use a different implementation in this role solving it via `failed_when`. 

> What about simply skipping the job instead, using when?
> We should be able to figure out if the required package is installed.

This is of course also a valid solution.
